### ISSUE TITLE
Move to latest PIN release

### ISSUE THREAD

**Issue by doegox** [SideChannelMarvels/Tracer#9]
https://software.intel.com/en-us/articles/pintool-downloads
rev 76991   Mar 24, 2016

**Comment by jevinskie** [comment]
FYI the Mac release disappeared from the download page for some reason. Here is a direct link for anyone interested: http://software.intel.com/sites/landingpage/pintool/downloads/pin-3.0-76991-clang-mac.tar.gz

**Comment by xinhuang** [comment]
Just make TracerPin work with latest PIN (3.7) on macOS, and here are the changes:

*For PIN 3.7*

1. `CODECACHE_ChangeMaxInsPerTrace` was deprecated somewhere after 3.4. On the documentation Intel didn't even mention it on the deprecated APIs list. So delete it if you don't use the `-cache` flag.  
2. PIN 3.7 is compiled with `-fno-exception`, so `try...catch` in the source code should be removed.

*For macOS*

3. On macOS, for some unknown reason if linked with `sqlite3`, the `Tracer.dylib` cannot be loaded. Tried compiling sqlite3 from scratch according to PIN's compilation flags, didn't work. Therefore the sqlite code should be removed, or the runtime error should be fixed.
4. The makefile should be changed: replace `.so` by `$(PINTOOL_SUFFIX)`. (Because macOS doesn't use `.so` but `.dylib`) The shell script `Tracer` should be also changed for macOS. (This should be the first bullet I guess ;)

**Comment by meme** [comment]
I've worked on this today and got TracerPIN compiled for Intel PIN 3.15. Unfortunately, PIN 3.x is severely limited as common functions such as `stat`, `fstat`, etc. are missing implementations. These are required by SQLite so I've been hacking away at implementing them individually, but with 7 functions  that have to be implemented from scratch, I'm hoping there's a better way. Regardless, if this is of interest (including these limitations), I'd be happy to make a PR.

**Comment by doegox** [comment]
well yeah, if you manage to revive the tracer with a decent version of PIN tools that would be great !!

**Comment by meme** [comment]
https://github.com/SideChannelMarvels/Tracer/pull/30

**Comment by doegox** [comment]
Thanks! closing this one.

**Comment by doegox** [comment]
you made someone happy today ;) https://twitter.com/doegox/status/1288985565128527872
